##* oh-my-zsh config
##* https://github.com/ohmyzsh/ohmyzsh/wiki/Settings
# Path to your oh-my-zsh installation.
export ZSH="$HOME/.config/oh-my-zsh"

# Theme
ZSH_THEME="agnoster"

# Plugins
# https://github.com/ohmyzsh/ohmyzsh/wiki/Plugins
plugins=(
  sudo    # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/sudo
  vscode    # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/vscode
  zsh-autocomplete    # https://github.com/marlonrichert/zsh-autocomplete
  zsh-syntax-highlighting    # https://github.com/zsh-users/zsh-syntax-highlighting
  )

# Days between update check
UPDATE_ZSH_DAYS=7

# History Stamps
HIST_STAMPS="yyyy-mm-dd"

# Load oh-my-zsh
source $ZSH/oh-my-zsh.sh


##* Personal config
# Set preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='nano'
else
  export EDITOR='nano'
fi

# History
HISTFILE=$HOME/.history

# Load Nord dircolors
# https://github.com/arcticicestudio/nord-dircolors
test -r "$HOME/.config/zsh/dir_colors" && eval $(dircolors $HOME/.config/zsh/dir_colors)

# Load Aliases
source ~/.config/aliases/alias